Tweaked linting job so it can be run by users locally. (#272)
* Consolidated lint and format

* Small tweaks

* test

* Check all return codes

* Removed test file

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -7,12 +7,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 <<<<<<< HEAD
+<<<<<<< HEAD
+=======
+>>>>>>> Tweaked linting job so it can be run by users locally. (#272)
     - name: Set up Python
       uses: actions/setup-python@v2
     - name: Fetch pull request branch
       uses: actions/checkout@v2
     - name: Fetch base master branch
       run: git fetch -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" master:master
+<<<<<<< HEAD
     - name: Install requirements
       run: python3 -m pip install -U -r .github/workflows/linter/requirements.txt
     - name: Format and lint notebooks
@@ -84,3 +88,21 @@ jobs:
 =======
       run: .github/workflows/linter/run_linter.sh
 >>>>>>> Added pre-commit and cleaned up linter (#265)
+=======
+    - name: Install requirements
+      run: python3 -m pip install -U -r .github/workflows/linter/requirements.txt
+    - name: Format and lint notebooks
+      run: |
+        set +e
+
+        .github/workflows/linter/run_linter.sh -t
+        RTN=$?
+
+        if [ "$RTN" != "0" ]; then
+          echo "There were problems formatting/linting the notebooks."
+          echo "Please run .github/workflows/linter/run_linter.sh locally to attempt to autofix the issues."
+          echo "If it can't be autofixed, please fix them manually."
+          echo "Then, commit the fixes and push again."
+          exit 1
+        fi
+>>>>>>> Tweaked linting job so it can be run by users locally. (#272)
